### PR TITLE
Preventing autocomplete

### PR DESCRIPTION
**Pull request by rahulkapoor90**
[Review on Reviewable](https://reviewable.io/reviews/prijindal/vitacademics-web/8)

### CODE REVIEW

**Comment by aneesh-neelam** [comment]
@rahulkapoor90: I'm guessing this disables the browser's autocomplete? Why would you want that?

**Comment by rahulkapoor90** [comment]
@aneesh-neelam just because after i login first time, then after that someone else can also use the same page and see the parent mobile number and login to my account. users don't want that i guess!

you can also change parent number to type='password'

**Comment by aneesh-neelam** [comment]
@rahulkapoor90: Since most websites don't do this, and the ones who do break the browser or password manager features, this is not recommended. You can turn off autocomplete in your browser or don't save the password. It's the user's choice. We must not make it for them. 

Besides, want to let a friend use your computer? You can use the guest session and incognito/private browsing for that. 

Also, neither the date of birth nor the parent's phone number is sensitive information. Sensitive enough for it to be hashed in the database. Let it be shown on the screen, even in the native apps.

**Comment by prijindal** [comment]
Maybe we can add a remember me feature here

**Comment by aneesh-neelam** [comment]
Remember Me is to keep you signed in.

**Pull request closed without merging**
